# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(null=True)),
                ('expected_date', models.TextField(null=True)),
                ('actual_date', models.TextField(null=True)),
                ('trial_date', models.TextField(null=True)),
                ('qc_date', models.TextField(null=True)),
                ('action_taken', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('cost', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_number', models.TextField(null=True)),
                ('jw_number', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('product', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('start_date', models.TextField(null=True)),
                ('target_date', models.TextField(null=True)),
                ('done_by', models.TextField(null=True)),
                ('actual_date', models.TextField(null=True)),
                ('cost', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
    ]
