# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myexcel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='details',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myexcel.Works'),
        ),
        migrations.AddField(
            model_name='works',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
