# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20160206_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed', to='ecommerce.Product'),
        ),
    ]
