# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20160207_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewedproducts',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
