# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20160220_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_availabe',
            field=models.BooleanField(default=False),
        ),
    ]
