# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0007_product_warranty_availabe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productcomments',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commentsflags',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.ProductComments'),
        ),
        migrations.AddField(
            model_name='commentsflags',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commented', to=settings.AUTH_USER_MODEL),
        ),
    ]
