# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20160221_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_cod_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_online_payment',
            field=models.BooleanField(default=False),
        ),
    ]
