# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 00:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instirepo_web', '0018_dropboxfilesforposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumesDropbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('parent_path', models.TextField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
                ('mime_type', models.TextField(blank=True, null=True)),
                ('modified', models.TextField(blank=True, null=True)),
                ('rev', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('bytes', models.IntegerField(blank=True, null=True)),
                ('expires', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
